Update README.md
mattburman/mattburman pull request #1
Opened 2020-07-06 22:18 UTC by PandelisZ

2020-07-07 08:38 UTC, mattburman requested changes
hmm, i cant quite put my finger on it, but i think this PR needs work

2020-07-09 08:17 UTC, sprusr requested changes

2020-07-09 08:17 UTC, sprusr commented on README.md
> +# Matt Burnman
```suggestion
# Matt Birdman

![birdman](https://user-images.githubusercontent.com/7497084/87015159-b493c780-c1d5-11ea-9bac-c281e1dc272a.png)
```

2020-07-09 08:32 UTC, mattburman commented on README.md
> +# Matt Burnman
close but no cigar

2020-07-09 10:20 UTC, PandelisZ commented
I've implemented the feedback and suggestions

2020-07-09 10:48 UTC, sprusr approved these changes
LGTM

2020-07-09 12:18 UTC, mattburman requested changes
whilst I appreciate the intent behind 6b801ba and deem it a valuable contribution, I feel it removes a certain essence of the project, thus I must request a minor modification, specifically around the middle columns of this diff

@PandelisZ

2020-07-09 12:20 UTC, mattburman commented
_does it say burning_? 😆

2020-07-11 15:15 UTC, closed without merging

2020-07-11 15:15 UTC, mattburman commented
Closed due to inactivity. If this is still an issue feel free to reopen. Thanks!